project:
  type: website
  output-dir: docs

website:
  title: "Roberto Licandeo, PhD"
  favicon: "images/logo_mini.png"
  google-analytics: "G-X8FBYR6RWS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - href: publications.qmd
      #   text: Publications
      # - href: projects.qmd
      #   text: Projects
      # - href: cv.qmd
      #   text: CV
    right:
      - icon: github
        href: https://github.com/rlicandeo
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=66RSKVsAAAAJ
      - icon: fingerprint
        href: https://orcid.org/0000-0003-4593-183X
      - icon: envelope
        href: mailto:robertolicandeo@gmail.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full