project:
  type: website
  output-dir: docs
website:
  title: "Roberto Licandeo, PhD"
  favicon: "images/logo_mini.png"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - icon: envelope
        href: mailto:robertolicandeo@gmail.com



